name: Build NW.js Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install NW.js Builder
      run: npm install -g nw-builder

    - name: Build application
      run: |
        npx nwbuild -v latest -p win32,win64 -o build/
        zip -r build.zip build/
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build.zip
